### ISSUE TITLE
Решения

### ISSUE THREAD

**Issue by imoisey** [spawn2010/problem_module#14]
Переделать механизм с решениями в системе.
Сейчас в системе к проблеме можно добавить только один вариант решения. Необходимо реализовать возможность добавлять несколько вариантов решения к каждой проблеме.

1. Вводим новую сущность Deсision. (id, problem_id, user_id, content, created_at)
2. Добавить миграцию с таблицей desicions для новой сущности Decision.
3. Сделать форму добавления решения в карточке проблемы. (добавить решение может любой пользователь системы)
4. Сделать вывод списка добавленных решений в карточке проблемы - ниже вывода самой проблемы. (содержимое, автор, дата добавления)

Для уже добавленных в системе решений, необходимо сделать миграцию которая выполнить преобразование из колонки decision таблицы problems в новую строку таблицы desicions.

Колонку decision в таблице problems пока оставить как есть, по ней будет отдельная задача.

**Comment by spawn2010** [comment]
Есть вопросы:
1. Как должна выглядеть форма добавления решения в карточке проблемы (отдельная кнопка на каждой карточке, поле с плейсхолдером типа "напишите решение" и т.д)
2. Схожий вопрос с выводом списка, в каком формате это должно быть (выпадающий список, просто список с решениями расширающий карточку и т.д)?

**Comment by imoisey** [comment]
> 1. Как должна выглядеть форма добавления решения в карточке проблемы (отдельная кнопка на каждой карточке, поле с плейсхолдером типа "напишите решение" и т.д)

Форма добавления примерно, как форма для добавления этого issue. Поле для ввода текста и кнопка добавить.
Для лучшего понимания можно добавить плейсхолдер

> 2. Схожий вопрос с выводом списка, в каком формате это должно быть (выпадающий список, просто список с решениями расширающий карточку и т.д)?

Аналогично странице со списком issue здесь. 
![image](https://user-images.githubusercontent.com/2510489/147497359-b643a264-0776-4a24-9110-aaf6f3c0c8f9.png)
